/*
 * DataSourcePanel.java
 *
 * Created on May 20, 2008, 3:05 AM
 */

package org.opennpo.mpres.gui;

/**
 *
 * @author  nate
 */
public class DataSourcePanel extends javax.swing.JPanel {
    
    /** Creates new form DataSourcePanel */
    public DataSourcePanel() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabPane = new javax.swing.JTabbedPane();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));
        add(tabPane);
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane tabPane;
    // End of variables declaration//GEN-END:variables
    
}
