/*
 * DataSourcePanel.java
 *
 * Created on May 20, 2008, 3:05 AM
 */

package org.opennpo.mpres.gui;

import java.util.List;
import java.util.ServiceLoader;
import java.util.ServiceLoader;
import java.util.ServiceLoader;
import java.util.Vector;
import javax.swing.JScrollPane;
import org.opennpo.mpres.ScriptItemSource;

/**
 *
 * @author  nate
 */
public class DataSourcePanel extends javax.swing.JPanel {
    private List<ScriptItemSource> sources;
    /** Creates new form DataSourcePanel */
    public DataSourcePanel() {
        initComponents();
        sources = new Vector<ScriptItemSource>();
        ServiceLoader<ScriptItemSource> loader = ServiceLoader.load(ScriptItemSource.class);
        if(loader!=null){
            for(ScriptItemSource src : loader){
                addSource(src);
            }
        }
    }
    
    public void addSource(ScriptItemSource src){
        tabPane.addTab(src.getTitle(), src.getIcon(), src.getComponent());//new JScrollPane(src.getComponent()));
        sources.add(src);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabPane = new javax.swing.JTabbedPane();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));
        add(tabPane);
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane tabPane;
    // End of variables declaration//GEN-END:variables
    
}
