drop  table "OpenNPO_MMS_Person";

create table "OpenNPO_MMS_Person" (
	"ID" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
	"FirstName" varchar(50),
	"MiddleName" varchar(50),
	"LastName" varchar(50),
	"CompanyName" varchar(50),
	"Parent1" INTEGER,
	"Parent2" Integer,
	"Spouse" INTEGER,
	"Gender" CHAR,
	"DOB" DATE,
	CONSTRAINT FK_PARENT1_ID FOREIGN KEY ("Parent1") REFERENCES "OpenNPO_MMS_Person"("ID"),
	CONSTRAINT FK_PARENT2_ID FOREIGN KEY ("Parent2") REFERENCES "OpenNPO_MMS_Person"("ID"),
	CONSTRAINT FK_SPOUSE_ID FOREIGN KEY ("Spouse") REFERENCES "OpenNPO_MMS_Person"("ID"),
	CONSTRAINT CHK_GENDER CHECK ("Gender" in ('M','F'))
);

create table "OpenNPO_MMS_Address" (
	
)

insert into "OpenNPO_MMS_Person"(	"ID",	"FirstName",	"LastName",		"Gender")
				          values(	0,		'John',			'Doe',			'M');
insert into "OpenNPO_MMS_Person"(	"ID",	"FirstName",	"LastName",		"Gender",	"Spouse")
				          values(	1,		'Jane',			'Doe',			'F',		0);
update "OpenNPO_MMS_Person" set "Spouse"=1 where "ID"=0;
insert into "OpenNPO_MMS_Person"(	"ID",	"FirstName",	"LastName",		"Gender",	"Parent1",	"Parent2")
				          values(	0,		'Billy',			'Doe',			 'M',	0,			1);
